name : Build and Deploy website

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Build Pelican
        run: |
          echo "Building Pelican website"
          pelican content -o output -s publishconf.py

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -m "Generate Pelican site" -b "gh-pages" output
          git push -f origin gh-pages
          echo 'Successfull deployment'


